name: Pre Release library
on:
  push:
    branches:
        - '*'         # matches every branch that doesn't contain a '/'
        - '*/*'       # matches every branch containing a single '/'
        - '**'        # matches every branch
        - '!main'   # excludes main

jobs:
  pre_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
            node-version: 22
            cache: 'npm'
            # Path to the lock file needs to be specified explicitly as it is not in the root of the repository
            cache-dependency-path: 'documentation-ui/package-lock.json'
      - name: Lint and build documentation UI JS package
        working-directory: documentation-ui
        run: |
          npm ci
          npm run lint
          npm run build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
